optimizer:
    weight_decay: 0.00
    lr: 1e-3
    type: adam

network: DGCNN
dataset: ShapeNet # ShapeNet, ShapeNetPart, ModelNet40, ScanNet
num_points: 2048 # 2048 for ShapeNet, 4096 for ModelNet40, 4096 for ScanNet
epochs: 100
batch_size: 32
acc_batches: 1
transform_mode: both

decay_rate: 0.996
mlp_hidden_size: 4096
projection_size: 256

k: 40
emb_dims: 1024
window_length: 3
dropout: 0.5
num_workers: 32

resume_ckpt: 